<?php

return [
    
    'PERMISSION_ERROR'=>"P401",
    'ADMIN_USER_TYPE'=>1,
    'DEFAULT_PAGINATE_LIMIT'=>10,
    'ADMIN_EMAIL'=>'imrancse94@gmail.com',

    'VALIDATION_ERROR'=>1000,
    'UNATHENTICATED_ERROR'=>4001,

    'ORDER_PENDING'=> 0,
    'ORDER_APPROVED'=> 1,
    'ORDER_REJECTED'=> 2,
    'ORDER_PROCESSING'=> 3,
    'ORDER_SHIPPED'=> 4,
    'ORDER_DELIVERED'=> 5,
    'ORDER_CANCELED'=> 6,

    'PRODUCT_ADD_SUCCESS'=>100,
    'PRODUCT_ADD_FAILED'=>-100,
    
    'PRODUCT_EDIT_FAILED'=>101,
    'PRODUCT_EDIT_SUCCESS'=>-101,
    
    'PRODUCT_GET_BY_ID_FAILED'=>-102,
    'PRODUCT_GET_BY_ID_SUCCESS'=>102,
    
    'PRODUCT_GET_LIST_FAILED'=>-103,
    'PRODUCT_GET_LIST_SUCCESS'=>103,
    
    'PRODUCT_DELETED_FAILED'=>-104,
    'PRODUCT_DELETED_SUCCESS'=>104,
    
    'LOGIN_FAILED'=>-105,
    'LOGIN_SUCCESS'=>105,
    
    'USER_SIGNUP_FAILED'=>-106,
    'USER_SIGNUP_SUCCESS'=>106,

    'ORDER_ADDED_FAILED'=>-107,
    'ORDER_ADDED_SUCCESS'=>107,
    
    'ORDER_EDITED_FAILED'=>-108,
    'ORDER_EDITED_SUCCESS'=>108,

    'ORDER_LIST_SUCCESS'=>109,
    'ORDER_LIST_FAILED'=>-109,

    'ORDER_GET_SUCCESS'=>110,
    'ORDER_GET_FAILED'=>-110,
    
    'ORDER_DELETE_SUCCESS'=>110,
    'ORDER_DELETE_FAILED'=>-110,
];