<?php

return [
    'VALIDATION_ERROR'=>1000,

    'PRODUCT_ADD_SUCCESS'=>100,
    'PRODUCT_ADD_FAILED'=>-100,
    
    'PRODUCT_EDIT_FAILED'=>101,
    'PRODUCT_EDIT_SUCCESS'=>-101,
    
    'PRODUCT_GET_BY_ID_FAILED'=>102,
    'PRODUCT_GET_BY_ID_SUCCESS'=>-103,
];