<?php

return [
    'VALIDATION_ERROR'=>1000,
    'UNATHENTICATED_ERROR'=>4001,

    'PRODUCT_ADD_SUCCESS'=>100,
    'PRODUCT_ADD_FAILED'=>-100,
    
    'PRODUCT_EDIT_FAILED'=>101,
    'PRODUCT_EDIT_SUCCESS'=>-101,
    
    'PRODUCT_GET_BY_ID_FAILED'=>-102,
    'PRODUCT_GET_BY_ID_SUCCESS'=>102,
    
    'PRODUCT_GET_LIST_FAILED'=>-103,
    'PRODUCT_GET_LIST_SUCCESS'=>103,
    
    'PRODUCT_DELETED_FAILED'=>-104,
    'PRODUCT_DELETED_SUCCESS'=>104,
    
    'LOGIN_FAILED'=>-105,
    'LOGIN_SUCCESS'=>105,
    
    'USER_SIGNUP_FAILED'=>-105,
    'USER_SIGNUP_SUCCESS'=>105,
];