
export default {
    
    "NO_IMAGE_PATH":"/img/no-image.jpg",
    
    "USER_TYPE_DEFAULT_ROUTE":{
        1:"dashboard",
        2:"order"
    },
    "order_status_list":{
        0:"PENDING",
        1:"APPROVED",
        2:"REJECTED",
        3:"PROCESSING",
        4:"SHIPPED",
        5:"DELIVERED",
        6:"CANCEL",
    },

    "ADMIN_USERT_TYPE":1,
    "BUYER_USERT_TYPE":2,

    // Status code
    'PRODUCT_ADD_SUCCESS':100,
    'PRODUCT_ADD_FAILED':-100,
    
    'PRODUCT_EDIT_FAILED':-101,
    'PRODUCT_EDIT_SUCCESS':101,
    
    'PRODUCT_GET_BY_ID_FAILED':-102,
    'PRODUCT_GET_BY_ID_SUCCESS':102,
    
    'PRODUCT_GET_LIST_FAILED':-103,
    'PRODUCT_GET_LIST_SUCCESS':103,
    
    'PRODUCT_DELETED_FAILED':-104,
    'PRODUCT_DELETED_SUCCESS':104,
    
    'LOGIN_FAILED':-105,
    'LOGIN_SUCCESS':105,
    
    'USER_SIGNUP_FAILED':-106,
    'USER_SIGNUP_SUCCESS':106,

    'ORDER_ADDED_FAILED':-107,
    'ORDER_ADDED_SUCCESS':107,
    
    'ORDER_EDITED_FAILED':-108,
    'ORDER_EDITED_SUCCESS':108,

    'ORDER_LIST_SUCCESS':109,
    'ORDER_LIST_FAILED':-109,

    'ORDER_GET_SUCCESS':110,
    'ORDER_GET_FAILED':-110,
    
    'ORDER_DELETE_SUCCESS':110,
    'ORDER_DELETE_FAILED':-110,

    'USER_LOGOUT_SUCCESS':111,
    'USER_LOGOUT_FAILED':-111,

    'AUTH_USER_SUCCESS':112,

}